# If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
services:
  calibre-web-automated-book-downloader:
    image: lklynet/fetchly:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /tmp/data/calibre-web/ingest:${INGEST_DIR:-/cwa-book-ingest}

  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
